image: docker.team23.de/docker/typo3/php-typo3:7.2

#services:
#  - mysql:latest
#
#variables:
#  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
#  MYSQL_DATABASE: testing
#  MYSQL_ROOT_PASSWORD: testing
#  typo3DatabaseName: testing
#  typo3DatabaseUsername: root
#  typo3DatabasePassword: testing
#  typo3DatabaseHost: mysql


before_script:
  - composer -vvv update

test:
  script:
  - .Build/vendor/bin/phpunit -c Tests/UnitTests.xml
  # - ./.Build/vendor/bin/phpunit -c Tests/FunctionalTests.xml --bootstrap .Build/vendor/typo3/testing-framework/Resources/Core/Build/FunctionalTestsBootstrap.php
