language: php

env:
  global:
    - TYPO3_PATH_ROOT=$PWD/.Build/public
    - typo3DatabaseName=typo3
    - typo3DatabaseHost=localhost
    - typo3DatabaseUsername=root
    - typo3DatabasePassword=

matrix:
  include:
    - php: 7.1
      env:
        - TYPO3VERSION="^8.7"
        - UNIT="1"
        - FUNCTIONAL="1"
        - ACCEPTANCE="1"
    - php: 7.2
      env:
        - UNIT="1"
        - FUNCTIONAL="1"
        - TYPO3VERSION="^9.5"
    - php: 7.2
      env:
      - TYPO3VERSION="^9.5"
      - BUILD_DOC="1"

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache

install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
  - phpenv rehash
  - rm -f composer.lock; composer require typo3/minimal:$TYPO3VERSION; git checkout composer.json
  - mkdir -p .Build/public/typo3conf/ext/
  - if [ "$ACCEPTANCE" = "1" ]; then curl -s -L -o chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip; fi
  - if [ "$ACCEPTANCE" = "1" ]; then unzip -o -d $HOME chromedriver_linux64.zip; fi
  - if [ "$ACCEPTANCE" = "1" ]; then chmod +x $HOME/chromedriver; fi

before_script:
  - if [ "$ACCEPTANCE" = "1" ]; then $HOME/chromedriver --url-base=/wd/hub & fi
  - if [ "$ACCEPTANCE" = "1" ]; then php -S 127.0.0.1:8888 -t .Build/public/ &>/dev/null & fi

script:
  - composer ci:static
  - if [ "$UNIT" = "1" ]; composer tests:unit; fi
  - if [ "$FUNCTIONAL" = "1" ]; composer tests:functional; fi
  - if [ "$ACCEPTANCE" = "1" ]; then composer tests:acceptance; fi
  - if [ "$BUILD_DOC" = "1" ]; composer build:doc; fi
