language: php

matrix:
  include:
    - php: 7.1
      env:
        - TYPO3VERSION="^8.7"
        - ACCEPTANCE="1"
    - php: 7.2
      env:
        - TYPO3VERSION="^9.5"

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache

install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
  - phpenv rehash
  - rm -f composer.lock; composer require typo3/minimal:$TYPO3VERSION; git checkout composer.json
  - mkdir -p .Build/public/typo3conf/ext/
  - export TYPO3_PATH_ROOT=$PWD/.Build/public
  - export typo3DatabaseName=typo3
  - export typo3DatabaseHost=localhost
  - export typo3DatabaseUsername=root
  - export typo3DatabasePassword=
  - if [ "$ACCEPTANCE" = "1" ]; then curl -s -L -o chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip; fi
  - if [ "$ACCEPTANCE" = "1" ]; then unzip -o -d $HOME chromedriver_linux64.zip; fi
  - if [ "$ACCEPTANCE" = "1" ]; then chmod +x $HOME/chromedriver; fi

before_script:
  - if [ "$ACCEPTANCE" = "1" ]; then $HOME/chromedriver --url-base=/wd/hub & fi
  - if [ "$ACCEPTANCE" = "1" ]; then php -S 127.0.0.1:8888 -t .Build/public/ &>/dev/null & fi

script:
  - composer ci:static
  - composer tests:unit
  - composer tests:functional
  - if [ "$ACCEPTANCE" = "1" ]; then composer tests:acceptance; fi
