version: "3"

services:

  # Use MariaDB as database server
  db:
    image: docker.team23.de/docker/mysql:5.7
    environment:
      # Provide a docker database by default
      MYSQL_ROOT_PASSWORD: "testing"
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker

  # PHP FPM service, running PHP 7.1
  php:
    image: docker.team23.de/docker/typo3/php-typo3:7.1
    # build: docker/php
    volumes:
      # As a convention we provide the project repository as /app
      - ./:/app/:cached
      - .:/app/Build/web/typo3conf/ext/c1_adaptive_images/
    depends_on:
      - db
    environment:
      TEAM23_DOCKER_PHP_ENABLE_XDEBUG: 1
      typo3DatabaseName: docker
      typo3DatabaseUsername: root
      typo3DatabasePassword: testing
      typo3DatabaseHost: db


